# Netlify 配置 - SSAT AI学习平台
# 更新于 2024-01-21 00:10:00 - 修复PDF解析和构建问题

[build]
  publish = ".next"
  command = "npm run build"
  
[build.processing]
  skip_processing = false
  
[build.processing.css]
  bundle = true
  minify = true
  
[build.processing.js]
  bundle = true
  minify = true
  
[build.processing.html]
  pretty_urls = true

# Next.js 15 支持
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # Node.js 版本
  NODE_VERSION = "18"
  # 确保支持ES模块和原生依赖
  NPM_FLAGS = "--legacy-peer-deps"
  # 启用PDF解析支持
  NODE_OPTIONS = "--max-old-space-size=4096"
  # AWS Lambda 兼容性
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"

# Next.js API路由会自动被 @netlify/plugin-nextjs 处理，无需手动重定向

# 安全头部
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self' *.supabase.co *.googleapis.com;"

# 静态资源缓存
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 生产环境变量
[context.production.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  # 确保PDF解析正常工作
  NODE_OPTIONS = "--max-old-space-size=4096"