'use client';

import { useState } from 'react';
import Link from 'next/link';
import { 
  Settings, 
  House, 
  BookOpen, 
  User,
  Clock,
  Brain,
  FileText
} from 'lucide-react';

export default function HomePage() {
  const [overallProgress] = useState(65);



  return (
    <div
      className="relative flex size-full min-h-screen flex-col bg-slate-50 justify-between overflow-x-hidden"
      style={{ fontFamily: 'Lexend, "Noto Sans", sans-serif' }}
    >
      <div>
        {/* Header */}
        <div className="flex items-center bg-slate-50 p-4 pb-2 justify-between">
          <h2 className="text-[#0e141b] text-lg font-bold leading-tight tracking-[-0.015em] flex-1 text-center">
            SSAT AI Learning
          </h2>
        </div>

        {/* App Description */}
        <div className="px-4 py-6">
          <div className="bg-gradient-to-br from-blue-600 via-blue-700 to-purple-800 rounded-xl p-6 text-white">
            <h3 className="text-xl font-bold mb-2">AI-Powered SSAT Learning</h3>
            <p className="text-blue-100 text-sm mb-4">
              Master vocabulary through spaced repetition and AI-generated practice questions tailored to your learning progress.
            </p>
            <div className="flex items-center gap-2 text-blue-100 text-xs">
              <Brain size={16} />
              <span>Smart vocabulary system with memory optimization</span>
            </div>
          </div>
        </div>


        {/* Main Actions */}
        <div className="px-4 py-2">
          <h3 className="text-[#0e141b] text-lg font-bold mb-4">Learning Tools</h3>
          <div className="space-y-4">
            <Link 
              href="/flashcard"
              className="block bg-white rounded-xl p-4 border border-[#d0dbe7] hover:shadow-lg transition-all duration-200 hover:scale-[0.98]"
            >
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 bg-gradient-to-br from-green-500 to-emerald-600 rounded-lg flex items-center justify-center">
                  <Brain size={24} className="text-white" />
                </div>
                <div className="flex-1">
                  <h4 className="text-[#0e141b] font-semibold text-base">Vocabulary Flashcards</h4>
                  <p className="text-[#4e7397] text-sm">Learn and review vocabulary with spaced repetition</p>
                </div>
              </div>
            </Link>

            <Link 
              href="/practice"
              className="block bg-white rounded-xl p-4 border border-[#d0dbe7] hover:shadow-lg transition-all duration-200 hover:scale-[0.98]"
            >
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 bg-gradient-to-br from-blue-500 to-indigo-600 rounded-lg flex items-center justify-center">
                  <BookOpen size={24} className="text-white" />
                </div>
                <div className="flex-1">
                  <h4 className="text-[#0e141b] font-semibold text-base">AI Practice Questions</h4>
                  <p className="text-[#4e7397] text-sm">SSAT-style questions generated by AI based on your progress</p>
                </div>
              </div>
            </Link>

            <Link 
              href="/grammar"
              className="block bg-white rounded-xl p-4 border border-[#d0dbe7] hover:shadow-lg transition-all duration-200 hover:scale-[0.98]"
            >
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 bg-gradient-to-br from-purple-500 to-pink-600 rounded-lg flex items-center justify-center">
                  <FileText size={24} className="text-white" />
                </div>
                <div className="flex-1">
                  <h4 className="text-[#0e141b] font-semibold text-base">Grammar Practice</h4>
                  <p className="text-[#4e7397] text-sm">Master SSAT grammar rules with interactive exercises</p>
                </div>
              </div>
            </Link>
          </div>
        </div>
      </div>

      {/* Bottom Navigation */}
      <div>
        <div className="flex gap-2 border-t border-[#e7edf3] bg-slate-50 px-4 pb-3 pt-2">
          <Link href="/" className="flex flex-1 flex-col items-center justify-end gap-1 rounded-full text-[#0e141b]">
            <div className="text-[#0e141b] flex h-8 items-center justify-center">
              <House size={24} fill="currentColor" />
            </div>
            <p className="text-[#0e141b] text-xs font-medium leading-normal tracking-[0.015em]">Home</p>
          </Link>
          <Link href="/practice" className="flex flex-1 flex-col items-center justify-end gap-1 text-[#4e7397]">
            <div className="text-[#4e7397] flex h-8 items-center justify-center">
              <BookOpen size={24} />
            </div>
            <p className="text-[#4e7397] text-xs font-medium leading-normal tracking-[0.015em]">Practice</p>
          </Link>
          <Link href="/grammar" className="flex flex-1 flex-col items-center justify-end gap-1 text-[#4e7397]">
            <div className="text-[#4e7397] flex h-8 items-center justify-center">
              <FileText size={24} />
            </div>
            <p className="text-[#4e7397] text-xs font-medium leading-normal tracking-[0.015em]">Grammar</p>
          </Link>
          <Link href="/flashcard" className="flex flex-1 flex-col items-center justify-end gap-1 text-[#4e7397]">
            <div className="text-[#4e7397] flex h-8 items-center justify-center">
              <Brain size={24} />
            </div>
            <p className="text-[#4e7397] text-xs font-medium leading-normal tracking-[0.015em]">Vocabulary</p>
          </Link>
          <Link href="/profile" className="flex flex-1 flex-col items-center justify-end gap-1 text-[#4e7397]">
            <div className="text-[#4e7397] flex h-8 items-center justify-center">
              <User size={24} />
            </div>
            <p className="text-[#4e7397] text-xs font-medium leading-normal tracking-[0.015em]">Profile</p>
          </Link>
        </div>
        <div className="h-5 bg-slate-50"></div>
      </div>
    </div>
  );
}